#!/bin/sh

set -e

WORKDIR=$AUTOPKGTEST_TMP
SRCDIR=$PWD

patch -p1 < debian/tests-patches/use_system_hwloc

dh_autoreconf 2>&1
dh_auto_configure 2>&1
dh_auto_build 2>&1
dh_auto_test 2>&1

cd $SRCDIR
patch -p1 -R < debian/tests-patches/use_system_hwloc
